# -*- mode: python ; coding: utf-8 -*-

block_cipher = None

a = Analysis(
    ['src/desktop_app.py'],
    pathex=[],
    binaries=[],
    datas=[
        ('templates', 'templates'),
        ('static', 'static'),
        ('src/config.py', '.'),
        ('src/web_app.py', '.'),
        ('src/photo_track.py', '.'),
        ('src/exif_reader.py', '.'),
        ('src/coord_converter.py', '.'),
        ('src/thumbnail.py', '.'),
        ('src/geo_coder.py', '.'),
        ('src/track_generator.py', '.'),
        ('src/route_planner.py', '.'),
        ('src/ai_generator.py', '.'),
        ('src/excel_exporter.py', '.'),
        ('src/weather.py', '.'),
    ],
    hiddenimports=[
        'flask',
        'jinja2',
        'PIL',
        'PIL.Image',
        'exifread',
        'dotenv',
        'requests',
        'sqlite3',
        'config',
        'exif_reader',
        'coord_converter',
        'thumbnail',
        'photo_track',
        'geo_coder',
        'track_generator',
        'route_planner',
        'ai_generator',
        'excel_exporter',
        'weather',
        'openpyxl',
        'webview',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)

pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.zipfiles,
    a.datas,
    [],
    name='roadbook',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon='static/assets/app.ico',
)
