@echo off
echo Stopping all RoadBook processes...
taskkill /F /IM python.exe 2>nul
echo Waiting for processes to exit...
timeout /t 2 /nobreak >nul
echo Starting RoadBook Web server...
python src/web_app.py
